[package]
name = "eRgol"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
rand = "0.9.0-alpha.1"
log = "0.4.21"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

